# Generated by Django 4.2.16 on 2024-11-22 18:58

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(upload_to=apps.blog.models.blog_thumbnail_directory),
        ),
    ]
