# Generated by Django 4.2.16 on 2024-11-22 23:39

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_category_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.blog.models.category_thumbnail_directory),
        ),
    ]
